### ISSUE TITLE
Charts are tiny when 2x2

### ISSUE THREAD

**Issue by IanSavchenko** [jeroenheijmans/advent-of-code-charts#23]
Just received an update with 2 charts in a row and now they are tiny on my laptop screen :( It was pretty hard to use mouse-over even before, but now it's even harder... 
Can I suggest reverting the change or adding some kind of minimal width with wrapping?

**Comment by jeroenheijmans** [comment]
@IanSavchenko Yeah, I also noticed on some of my leaderboards that my changes didn't go over so well. Especially when there's many members on the leaderboard.

I'll see if I can revert or update this change slightly. To make sure I'd cover your case as well, could you share the number of members on your board, or perhaps even a (blurred if you want to anonimize it) screenshot?

**Comment by IanSavchenko** [comment]
I have 13 inch MacBook Pro + latest Chrome.

So this is how it looks with almost 50 people when I'm full screen and with 80% scaling (I usually split screen in two when solving tasks, so in this way can see all the text in AoC website).
<img width="1440" alt="screen shot 2018-12-09 at 18 58 44" src="https://user-images.githubusercontent.com/4881952/49700875-c752ae80-fbe4-11e8-82b2-c043561c4657.png">

Same state in dev tools 
<img width="933" alt="screen shot 2018-12-09 at 19 05 52" src="https://user-images.githubusercontent.com/4881952/49700925-8b6c1900-fbe5-11e8-841b-074d013b3b55.png">



Just noticed that when I reset scaling to 100% and reload the page, it goes back to normal state, as it was before all the updates. So there is already scaling logic, it's just not dynamic! I think it's probably fine, but maybe slightly bigger `min_width` would be good.

**Comment by mebeim** [comment]
Agreed, got a 22 inch monitor (latest extension version and latest Chrome) on my home PC, and charts look pretty bad :\ They were way better when displayed one under another. 

Here's a screenshot from my PC: ![screenshot](http://i.imgur.com/abJzvw2.png)

**Comment by jeroenheijmans** [comment]
@IanSavchenko @mebeim Oh my you have a lot of friends! 😅 

I'll push a fix in a second, and will release a patch to the extension stores in the coming hours, so all should be well again come Day 10 of advent!

PS. I have less friends and a QHD screen, so I made a button to opt _in_ on the 2x2 visualization (defaults to off, persists in localStorage):

![image](https://user-images.githubusercontent.com/1590536/49701398-40093900-fbec-11e8-8ebe-c33c585843ec.png)

**Comment by mebeim** [comment]
Cool button addition, good job :+1: :smile:
