### ISSUE TITLE
Podium doesn't show silver star results in medal overview

### ISSUE THREAD

**Issue by shrx** [jeroenheijmans/advent-of-code-charts#25]
See screenshot, a silver star is missing on day 8.

![screenshot](https://i.imgur.com/52WrGYP.png)

**Comment by shrx** [comment]
I'm using the firefox extension btw.

**Comment by jeroenheijmans** [comment]
It's the same case. The overview could use some love.

I like the suggestions, hoping I got them right. Summarizing:

- always show all medals, for both 2 stars' podiums
- explicitly show lack of a medal, at the position where it would've been

**Comment by IanSavchenko** [comment]
Looks good!
