### ISSUE TITLE
Improve tooltips for charts (at least for star-based data points)

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/advent-of-code-charts#3]
All chart.js charts in the extension have tooltips for points, which currently just show a single data value (e.g. a timestamp). For example:

![tooltip example](https://user-images.githubusercontent.com/1590536/34079590-e3b07a76-e330-11e7-885e-40c14dfe4a3d.png)

Just showing the datapoint's Y value isn't too bad, but there could be more info, better formatted. Since most (if not all?) charts have points representing stars, it makes sense to pick this issue up for all charts at once.

**Comment by rawling** [comment]
If you sort the y-axes for #2 so that they are "cumulative x at time" (rather than, what is it at the moment, "x at time, plus x for earlier puzzles that were completed later than time"?), then it would be good to have:
- puzzle number & part (since you won't be able to work this out from order along the trend line any more)
- points or medal gained

**Comment by jeroenheijmans** [comment]
Thanks for the suggestion @rawling! Given that there's only a few days of advent left, and that I want to spend time finishing my other pet project ([the unofficial AoC survey](https://www.reddit.com/r/adventofcode/comments/a3fknt/unofficial_aoc_2018_participant_survey/)), it might be next year before I get to this.

**Comment by rawling** [comment]
Yeah, fair enough :D

Thanks for everything, it's much better than the default, and good luck for
the rest of the year.

**Comment by jeroenheijmans** [comment]
It was somewhat hard to get the actual day/star combi in the tooltips, but the pushed fix is at least something...

**Comment by jeroenheijmans** [comment]
Interesting, GitHub 'thinks' I closed this in Dec 2019. In fact I only just now merged that PR. Will release a fix to the browser stores soon too.
