### ISSUE TITLE
Hacktober-updates for dependencies

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/advent-of-code-charts#36]
Since Advent of Code is a yearly thing, I also update dependencies yearly. This year I'm explicitly tagging an issue for "hacktoberfest" should someone want to take a shot at updating the dependencies. Most importantly chart.js should be updated to enable #33.

Note that this repository does _not_ contain proper unit tests. Please doe a proper manual regression test to see if everything keeps working after you change something.

PS. This _is_ a largely easy issue, and good for newcomers who want to learn how to open PRs and do OSS contributions.

**Comment by fbologni** [comment]
Hi, I wish to work on that one 👍🏻

**Comment by jeroenheijmans** [comment]
@fbologni Nice!

Be careful to wait a couple of days before creating the PR though, from the Hacktober rules:

> Yes, all pull requests created between Oct 1 and Oct 31 will count, regardless of when you register for Hacktoberfest. Pull requests created before Oct 1 but merged or marked as ready for review after do not count.

**Comment by jeroenheijmans** [comment]
Feel free to ping me here if you need help, and I'll also hang around [the contributing.today hacktoberfest Discord (invite top-right on the site)](https://www.contributing.today/) if you want to ask me questions.

**Comment by jeroenheijmans** [comment]
PS. There's [a `advent-of-code-charts` channel in the contributing.today Discord](https://discord.gg/rF8GBrP) where I'll be if anyone has hacktoberfest-related questions!
