### ISSUE TITLE
Feature Proposal: Show table with per-day time and points

### ISSUE THREAD

**Issue by pankdm** [jeroenheijmans/advent-of-code-charts#39]
Hi there! 
First of all, `advent-of-code-charts` is great extension and I enjoy using it a lot while solving AoC!

One thing that's been lacking for me on the main website is the ability to see per day timings and correspondingly awarded points. So I've been hacking a prototype heavily based on your extension. The current state looks like this:

<img width="914" alt="Screen Shot 2020-12-05 at 12 25 03 PM" src="https://user-images.githubusercontent.com/426145/101262679-55d76900-36f5-11eb-9906-6bbdb600947e.png">

Question: would you like to have such functionality as a part of your extension? If so I can submit a pull request with my code. Otherwise I would probably go and publish a new extension with only such functionality included.

**Comment by kindermoumoute** [comment]
I would love to visualize delta bewteen parts (part 2 - part 1) in this table. It's a better metric for people who solve these puzzles later in the day.

**Comment by jeroenheijmans** [comment]
@pankdm Yes! That table sounds like a great addition!

Feel free to post a PR I'd be happy to merge it and try and get another version out, if it's not to late into December.

@kindermoumoute I see you also opened #40 and I think that's a great suggestion too! Let's see if we can get @pankdm's PR in first, and follow up in #40 for your stuff?

**Comment by pankdm** [comment]
@jeroenheijmans Sounds great! I've submitted a pull request https://github.com/jeroenheijmans/advent-of-code-charts/pull/42 for this issue.
As a disclaimer - I am a fairly beginner in JS, so the code might be a little rough, but I am happy to iterate on it to get it merged.

**Comment by jeroenheijmans** [comment]
Thx for this PR @pankdm ! <3

I've started looking at it. Adding a couple of commits on top of your suggestions before merging. Unfortunately not done yet and work coming up, but I'll try to squeeze in time soon to finish up and get it out to the extension stores!

PS. No worries about JS level, any help is much welcome! We all start somewhere. And, by the way, please do not take this extension's code as "exemplary", it's far from that. It's not the _worst_ in the world, but take it with a grain of salt 😉 It's been written in "true AoC fashion".

**Comment by pankdm** [comment]
Cool, awesome! Looking forward to it. My friends keep asking how to get these nice graphs without going through the pains of cloning the repo and building it locally, so hopefully we can have it published before AoC ends 😄

**Comment by jeroenheijmans** [comment]
@pankdm Thank you so much for this cool addition! I ran off with it and added a bunch of tweaks, I hope you enjoy them and would agree they improve things. If I broke something of killed a useful feature in the process, please let me know and we'll figure something out.

I loved the feature request in #40 so much that I tried to fix it with this PR as well. It's now merged, I'll work soon on an updated version of the extension.

**Comment by jeroenheijmans** [comment]
I'm gonna close this issue as I think the new version 4.2.0 will resolve it. I do watch closed issues so you could post here, or in a new issue, if there's sth up.

**Comment by pankdm** [comment]
Thanks for additions, @jeroenheijmans!  It does look pretty cool now. I have some additional feedback though:
<img width="891" alt="Screen Shot 2020-12-08 at 12 11 22 PM" src="https://user-images.githubusercontent.com/426145/101536300-aa295580-394e-11eb-8199-cc4dc1ed89b2.png">

- I would add an option to sort by `Total Points` since this is official way how points are granted.
- Potentially having table title be clickable to select that sorting would make a lot of sense.
- I personally don't like have `Delta Time` sorting **by default** since this is non-official scoring. Probably having by `Total Points` and `Part Time 2` a default would be better.
- Delta Timings column shouldn't be highlighted when other sorting mode is selected - that looks unexpected.
- Having `Delta Time Rankings` as title is a little confusing, since there are many different columns. Probably generic `Daily Stats` or `Per Day Rankings` would be a better fit.

**Comment by jeroenheijmans** [comment]
Thx for your feedback. I'm afraid I made a few mistakes and/or calls that tend to get rushed by when hacking away at something like this extension :)

Let's chat about your points:


> - It looks like sorting by Completion Time sorts weirdly - I see that 01:40:39 in screenshot goes before 00:38:19

I've found a repro on one of my own leaderboards too, certainly something to track down and fix!

> - I would add an option to sort by Total Points since this is official way how points per day are granted.

That does make sense. I found it a lot less interesting myself, might've overlooked that this was actually an important one for you. (Even though I'm not sure what you mean by "official", since there _are_ no daily private leaderboard rankings to my knowledge? And the global daily leaderboards are sorted per star by time or rank on that day? - But that's semantics, a sort on all three "Total Points" does add value).

> - Potentially having table title be clickable to select that sorting would make a lot of sense.

Yeah, that might be better UX, even though it's less discoverable. Good suggestion!

> - I personally don't like have Delta Time sorting by default since this is non-official scoring.

Again, I'm not sure what you mean by "official"? And on a subjective note, I prefer the "Delta Time" aspect of this table, as it truly adds something I see a lot on e.g. Reddit: an option to do a bit of timezone-agnostic comparison. Whereas "Total Points" is just another "of the same" kind of graph.

I made it so that once you change the sorting, it will persist through localStorage. So you'd only need to change it once.

I realize this is a subjective change, and it might be sad since you really came up with the idea in the first place. Hope you understand the different default though?

> - Delta Timings column shouldn't be highlighted when other sorting mode is selected - that looks unexpected.

Yes, totally! Result of hacking around too much 😊 

> - Having Delta Time Rankings as title is a little confusing, since there are many different columns. Probably generic Daily Stats or Per Day Rankings would be a better fit.

Agreed!

----

Let me move the points we agree on to a fresh story at the very least, and see where we go from there. It might be the weekend before I get to more work on it though (esp. publishing is a tad tedious).

**Comment by pankdm** [comment]
> Even though I'm not sure what you mean by "official", since there are no daily private leaderboard rankings to my knowledge?

Actually there is `Local Score` sorting method that scores based on sum of `Total Points` for each day. That's what I meant that sorting by `Total Points` in some sense an official way of declaring who got better at that day:

<img width="863" alt="Screen Shot 2020-12-08 at 2 30 55 PM" src="https://user-images.githubusercontent.com/426145/101553397-65f77e80-3969-11eb-9a2f-854d07129916.png">

>  And the global daily leaderboards are sorted per star by time or rank on that day?

Ah, yes. That's true. There is no global daily leaderboard that would be a sum of both points.

**Comment by pankdm** [comment]
> I realize this is a subjective change, and it might be sad since you really came up with the idea in the first place. Hope you understand the different default though?

Yeah, that's fine. I am probably biased and don't really feel the need for timezone-specific change since the problems appear at almost perfect time: 9pm local time  😛 . I guess it's really painful for folks in Europe and if you see a lot of asks for that on reddit that would additionally justify it. 
Having the different default is not really a big deal then and might promote more stress-free participation for inconvenient timezones.

**Comment by pankdm** [comment]
> It might be the weekend before I get to more work on it though (esp. publishing is a tad tedious).

That's perfectly fine as well. I actually see a lot of value in getting the first version in (what you did today) and then iterating on UX improvements for next release.
