### ISSUE TITLE
Feature proposal: add a graph of delta between part2 and part1 time to resolve

### ISSUE THREAD

**Issue by kindermoumoute** [jeroenheijmans/advent-of-code-charts#40]
Since many of the participants can't solve puzzle at the very start of the day I find the following metric more interesting: time difference bewteen part2 and part1 . It would be so cool to have one or many visualisations of this in this plugin.

**Comment by jeroenheijmans** [comment]
This sounds like a great addition! I think it can be done in three complementary ways:

1. Update #39's table and add it as a column
2. See if we can make the table sortable (that might require a separate issue though)
3. Add a graph to show this delta for each day (probably as the 3rd graph, right after `Leaderboard (Stars)`)

@kindermoumoute Would you be interested in creating a PR? Or was it just a suggestion and shouldsomeone/I pick it up? Either's fine (but PRs I'd merge only this year if they don't come too late into December), just need to know.

**Comment by kindermoumoute** [comment]
It's a suggestion! :-)

**Comment by jeroenheijmans** [comment]
Loved the suggestion! Slipstreamed it in PR #42 follow up commits. At least part 1 and 2.

A graph would be nice (item 3), we'll see if that pops up as a fresh feature request someone wants to work on.

**Comment by jeroenheijmans** [comment]
Coming soon in 4.2.0
