### ISSUE TITLE
Improve new table with times and deltas

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/advent-of-code-charts#44]
In #39 we introduced a new table with stats. Some improvements are needed:

1. Fix bug where sometimes Completion Time sorts incorrectly
2. Add option to sort on "Total Points"
3. Make table headers clickable for sorting
4. Only highlight the column being sorted on, not always the delta time column
5. Improve the header to be not so specific to "Delta time" since the stats are broader, maybe "Stats per Day"?

----

Under discussion would be a change to the default sort option. I personally still lean towards keeping the "Delta" sort as default, since it is useful for timezone-agnostic comparisons...

**Comment by jeroenheijmans** [comment]
Example of bug (bullet 1 above): 

![incorrect sorting](https://user-images.githubusercontent.com/1590536/101549143-67e33100-39ad-11eb-9a47-fc101161503d.png)

Some of the data, first the incorrect row:

```
        "6": {
          "1": {
            "get_star_ts": "1544125108"
          },
          "2": {
            "get_star_ts": "1544133272"
          }
        },
```

And those for other users:

```
        "6": {
          "1": {
            "get_star_ts": "1544080254"
          },
          "2": {
            "get_star_ts": "1544081946"
          }
        }

        "6": {
          "1": {
            "get_star_ts": "1544075704"
          },
          "2": {
            "get_star_ts": "1544076961"
          }
        },

        "6": {
          "1": {
            "get_star_ts": "1544086376"
          },
          "2": {
            "get_star_ts": "1544086568"
          }
        },

        "6": {
          "1": {
            "get_star_ts": "1544105798"
          },
          "2": {
            "get_star_ts": "1544106903"
          }
        },
```

**Comment by pankdm** [comment]
> Fix bug where sometimes Completion Time sorts incorrectly

Actually it seems like intentional behavior 😄 
It's just probably better named as `By Total Points` sorting as that's what current implementation uses: https://github.com/jeroenheijmans/advent-of-code-charts/blob/master/src/js/app.js#L539-L543

**Comment by pankdm** [comment]
Thanks a lot @jeroenheijmans!
