### ISSUE TITLE
During a live event, charts only compare up to the current day, but including in previous (and completed) events

### ISSUE THREAD

**Issue by FrenchMasterSword** [jeroenheijmans/advent-of-code-charts#47]
If you open a private leaderboard, and check it for a past year like 2019, you can only get users times from day 1 to, as of today, 11, and users are only compared on this range, even though data for the 25 days is available.

**Comment by jeroenheijmans** [comment]
I don't think I follow? I've opened up one of my private leaderboards for 2019 and it shows everything beyond today's date (14th when taking the screenshot) just fine? See this:

![image](https://user-images.githubusercontent.com/1590536/102071782-4052f500-3e01-11eb-961c-f3811bab6080.png)

Could you provide steps to reproduce the bug, and add more details (or even the leaderboard json, anonimized) that causes this behavior?

**Comment by FrenchMasterSword** [comment]
I currently cannot reproduce the issue on my end, which is even more confusing since seemingly nothing changed in the repository.

**Comment by jeroenheijmans** [comment]
Ok, thx for getting back to us! <3

Happy puzzling!
