### ISSUE TITLE
UI and UX issues with filled leaderboards

### ISSUE THREAD

**Issue by Kroppeb** [jeroenheijmans/advent-of-code-charts#70]
I'm in one of the official kotlin leaderboards, and it's filled with 200 people, which results in some ui issues.

![image](https://user-images.githubusercontent.com/7889478/205224793-83525d8f-cc38-44ce-bd14-70e69a3869db.png)

**Comment by Kroppeb** [comment]
The graph is really small and the title of the graph overlaps with the users

**Comment by jeroenheijmans** [comment]
I see your point :D

I'm also on such a leaderboard, equally unusable. A half-baked workaround currently is to switch this toggle:

!["responsive" button](https://user-images.githubusercontent.com/1590536/205312941-e294fbcf-2c95-43fe-9607-2bd5f4754e07.png)

But it would be good to get a proper fix in for this. Not sure what that'd be, if ChartJS offers anything for this situation. Would need to investigate.

PS. I'm extremely busy this December, so no promises if/when I'd get to this, sorry!

**Comment by jeroenheijmans** [comment]
Going to look into this now as the final thing to do before I let it sit till fall (and know if there's gonna be a 2023 AoC at all).

Have done a bunch of things in #79 already including #81 upgrade of Chart.js, which changed this behavior already a lot. Right now the legend just clips its content:

![image](https://user-images.githubusercontent.com/1590536/211154623-691c9cd0-e2ed-4f62-bcd2-ff9ef4a34c50.png)

Still not great so I want to improve it. Current thinking is for leaderboards with more than N (=40?) people on it, to

- Make everyone except the "currently logged in user" (if known) less opaque.
- Hide legend items for all except (1) the "currently logged in user" (if known) and (2) the top N players

**Comment by jeroenheijmans** [comment]
Various different improvements are incoming in a second:

- (if logged in user is known) z-index of the logged in user on top of things
- (if logged in user is known) extra thick line and points for logged in user
- for large leaderboards all lines get muted (transparent) a bit
- legend will only show logged in user (if known) + 40 (or 25 on small viewports) entries (lines for others are still shown though)
- "responsive" mode has been removed for now as it was buggy

Screenshot sneak peek:

![image](https://user-images.githubusercontent.com/1590536/211201344-47e039e4-c827-468c-9cb3-26853974c0ed.png)
