### ISSUE TITLE
Not working for 2022?

### ISSUE THREAD

**Issue by andybergon** [jeroenheijmans/advent-of-code-charts#72]
![image](https://user-images.githubusercontent.com/5220825/205567224-7608c566-a5cd-47d8-9ef7-5ce09448bf02.png)

Tried both on macOS and Windows (only Chrome, no FF yet) and the plugin is greyed out.
Tried re-installing multiple times.

Is it a me problem?

**Comment by jeroenheijmans** [comment]
Hmmm, for me it's working in Chrome (both home Win10 PC and work Win10 laptop) and Firefox (work WIn10 laptop). I've not heard any reports from other users or colleagues either. Also tried removing and reinstalling it in Chrome just now, that also works for me.

Could you investigate a little bit more, share any kind of logs or other details that might be helpful?

**Comment by andybergon** [comment]
Oh,it runs on `"run_at": "document_end"`.
I just didn't scroll enough.

**Comment by jeroenheijmans** [comment]
Haha 😅 phew glad it worked out! Thanks for getting back to us. Happy puzzling!
