### ISSUE TITLE
Charts no longer correct

### ISSUE THREAD

**Issue by mherceg** [jeroenheijmans/advent-of-code-charts#8]
It seems the aoc has changed something since the last year when the graphs were correct. The charts aren't correct anymore.

**Comment by jeroenheijmans** [comment]
Yes, you're right. Seems the format of the json has changed. Don't worry, this is related to #7, and I will fix up the extension soon, hopefully no later than nov 30th!

**Comment by mherceg** [comment]
Hey, the timestamp format change in the .json. I've created this (#9) PR that fixes it for 2017.

**Comment by jeroenheijmans** [comment]
Thank you for the PR, works like a charm! The 2017 charts should start working again soon (once the Chrome extensions store picks up v2.0.0).

Still a few things to do for the 2018 version, but I'll work on those in the next few days.

**Comment by jeroenheijmans** [comment]
Version 2.0.0 landed in the Chrome store. The extension should automatically update (possibly after visiting the "extensions" page and/or restarting Chrome), on my machine it's showing the old charts again.

Thx again @mherceg !
