### ISSUE TITLE
Improve "thick line for logged in user" feature

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/advent-of-code-charts#86]
With v6.0.0 a feature to detect the "Logged In User" was added. It is used to make "your own" line in graphs stand out more. [It was pointed out on Reddit](https://www.reddit.com/r/adventofcode/comments/107nknu/comment/j3oz3pg/?utm_source=share&utm_medium=web2x&context=3) that this is a bit much, especially for (very) small leaderboards.

The suggestion there was also made to make it a toggle/setting. That's certainly a viable option.

I'd like to consider alternatives too (e.g. making the thickness a bit less so, and/or doing it only for large leaderboards), because "yet another setting" also has a cost attached (for UX, and for maintenance).

To be decided how to proceed, but for sure something to tweak.

See #79.

**Comment by jeroenheijmans** [comment]
I've decided _not_ to introduce a 'toggle' for this, because I dislike apps with too many settings. Instead, I've _strongly_ reduced the effect of extra thickness, so we can serve both cases.

For large leaderboards only that little bit is needed now anyways as the alpha is also lowered for others:

![image](https://user-images.githubusercontent.com/1590536/211650012-4c56a84c-22a3-40ad-93fc-0dedc1aacac0.png)

And for the redditor's question with smaller leaderboard, "your" line is now only a wee bit thicker so not as obtrusive anymore:

![image](https://user-images.githubusercontent.com/1590536/211650136-88f72535-dd03-4d57-971e-820c967be8e3.png)

I know that last one doesn't fully 'solve' the request to be able to toggle it to regular mode, but I really want to avoid having a ton of toggles in the app. Hope that makes sense.

Commit and plugin update forthcoming.

**Comment by SuperTux88** [comment]
Yes, I agree that too many options aren't necessarily better. As a user I like to have many options, but as a dev I also know it's not easy to add many options with good UX so non-power-users don't get overwhelmed. And that's also why I wasn't really sure if I should even ask for it, as I also didn't really have a good solution for it. But the thinner-by-default line now works quite well. it's still pretty visible on crowded leaderboards, but also works ok-ish on smaller leaderboards. :+1: I still have one leaderboard where I was racing with another person and we were pretty close for multiple days, but the new percentage view also already improves the visibility with close lines and it's visible as soon as we are 2 or more points apart. So probably good enough.

I just had another idea: what if the highlighted line is done with hovering over the names/lines? That could help to also quickly highlight other lines in a big board (without needing to disable everybody else). But I also don't know how easy that is and what it does to performance on big boards? :thinking: So not sure if it's worth it, but if you think it is doable and could be useful, I can create a separate issue about it.

But the new version already solves my issue good enough, so thanks for the quick update :heart: Everything else is really just "nice to have" territory.

**Comment by jeroenheijmans** [comment]
Thx for your reply and extra thoughts! I've taken the liberty of writing up #88 with your input. I think I will let that sit for some time, at the least until I know if a 2023 edition of AoC is gonna happen.
