### ISSUE TITLE
[BUG] First star always gives gold medal in first graph

### ISSUE THREAD

**Issue by diogotcorreia** [jeroenheijmans/advent-of-code-charts#95]
It seems like people that complete the first star of each day always get a "gold medal" in the podium graph.

![image](https://github.com/jeroenheijmans/advent-of-code-charts/assets/7467891/1fea2559-cbe1-4210-bf2e-e68da1376c8b)

**Comment by jeroenheijmans** [comment]
Both stores have accepted v6.2.1 and things should be fixed now (as soon as your addon updates or gets forced-updated by yourself :D).

**Comment by diogotcorreia** [comment]
Thanks a lot for the work and the awesome extension @jeroenheijmans!
Happy AoC :)
